export default {
    //chats
    ADD_MESSAGE_REQUEST: 'ADD_MESSAGE_REQUEST',
    ADD_MESSAGE_SUCCESS: 'ADD_MESSAGE_SUCCESS',
    ADD_MESSAGE_ERROR: 'ADD_MESSAGE_ERROR',

    GET_ALL_USER_CHATS_REQUEST: 'GET_ALL_USER_CHATS_REQUEST',
    GET_ALL_USER_CHATS_SUCCESS: 'GET_ALL_USER_CHATS_SUCCESS',
    GET_ALL_USER_CHATS_ERROR: 'GET_ALL_USER_CHATS_ERROR',

    //users
    LOGIN_USER_REQUEST: 'LOGIN_USER_REQUEST',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_ERROR: 'LOGIN_USER_ERROR',

    SIGNUP_USER_REQUEST: 'SIGNUP_USER_REQUEST',
    SIGNUP_USER_SUCCESS: 'SIGNUP_USER_SUCCESS',
    SIGNUP_USER_ERROR: 'SIGNUP_USER_ERROR',
}